//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubPortalMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Album
    {
        public Album(){
            HinhAnh = "~/Areas/Admin/Resource/HinhAnh/addImg.jpg";
            Video = "~/Areas/Admin/Resource/Video/addImg.jpg";
        }
        public int ID { get; set; }
        public string TieuDe { get; set; }
        [DisplayName("Tải hình ảnh lên")]
        public string HinhAnh { get; set; }
        [DisplayName("Tải video lên")]
        public string Video { get; set; }
        public string MoTa { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
        [NotMapped]
        public HttpPostedFileBase VideoFile { get; set; }
    }
}
