//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubPortalMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ChoXetDuyet
    {
        public int ID { get; set; }
        public int IDNguoiDK { get; set; }
        public string TrangThai { get; set; }
        [ForeignKey("IDNguoiDK")]
        public virtual DangKy DangKy { get; set; }
    }
}
