//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubPortalMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DangKy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DangKy()
        {
            this.ChoXetDuyet = new HashSet<ChoXetDuyet>();
        }
    
        public int ID { get; set; }
        [Required]
        [Display(Name = "Họ và Tên")]
        public string Ten { get; set; }
        [Required]
        [Display(Name = "Mã số sinh viên")]
        public string MSSV { get; set; }
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required]
        [Display(Name = "Số điện thoại")]
        public string SDT { get; set; }
        public DateTime? NgayDangKy { get; set; }
        [Required]
        [Display(Name = "Lý Do Đăng Ký")]
        public string LyDoDkyCLB { get; set; }
        public int IdTv { get; set; }
        public int IDCLB { get; set; }
        [ForeignKey("IdTv")]
        public virtual ThanhVien ThanhVien { get; set; }
        public virtual ICollection<ChoXetDuyet> ChoXetDuyet { get; set; }
    }
}
