//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubPortalMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class NhiemVu
    {
        public int ID { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string TenFile { get; set; }
        public string ContentType { get; set; }
        public byte[] File { get; set; }
        public DateTime ThoiGianKetThuc { get; set; }
        public int IdCLB { get; set; }
        public virtual ICollection<NhiemVu_ThanhVien> NhiemVu_ThanhVien { get; set; }
    }
}
