//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubPortalMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SuKien
    {
        public int ID { get; set; }
        public string TieuDeSK { get; set; }
        public string MoTa { get; set; }
        public DateTime NgayBatDau { get; set; }
        public DateTime NgayKetThuc { get; set; }
        public string NoiDung { get; set; }
        public string KetQua { get; set; }
        public string DiaDiem { get; set; }
        public string HinhThuc { get; set; }
        public string TenFile { get; set; }
        public string ContentType { get; set; }

        public byte[] File { get; set; }
        public int IdLoaiSK { get; set; }
        public int IdCLB { get; set; }
        [ForeignKey("IdCLB")]
        public virtual CLB CLB { get; set; }
        [ForeignKey("IdLoaiSK")]
        public virtual LoaiSuKien LoaiSuKien { get; set; }
    }
}
